### ISSUE TITLE
你好，请问sd partition制作虚拟系统后30Gb的分区空白

### ISSUE THREAD

**Issue by ghost** [ln93/kosmos_chs_tutorial#3]
请问照你的教程，在制作SD Partition的虚拟分区后，成个进入了破解系统。
但是TF卡上30GB的分区在电脑上查看是空白的，没有任何文件，请问这样正常吗？

**Comment by ln93** [comment]
对于分区形式的虚拟系统，如果制作正确，tf卡上30g的分区在windows电脑上应当是无法打开的——因为它是一个加密的分区。
如果你能打开这个分区，而且发现分区内是空的，这是不正常的。
一种可能是你实际上制作了文件形式的虚拟系统，因此没有用上那30G的分区。
