### ISSUE TITLE
图片全都看不到了，不知道是不是我的网络问题

### ISSUE THREAD

**Issue by HopeZZZ** [ln93/kosmos_chs_tutorial#4]

**Comment by ln93** [comment]
文中所用的图片存放在库中的imgs文件夹内。你可以进入imgs文件夹看看能否预览这些图片。

**Comment by HopeZZZ** [comment]
> 文中所用的图片存放在库中的imgs文件夹内。你可以进入imgs文件夹看看能否预览这些图片。

那应该是我的网络问题啦，有的网络就能查看到。
